### ISSUE TITLE
Usage with gulp-stylus

### ISSUE THREAD

**Issue by Benew** [maxmx/bootstrap-stylus#101]
Hi! Help needed. Can't figure how to use the package with [gulp-stylus](https://github.com/stevelacy/gulp-stylus).

Couldn't find help in closed issues. gulp-stylus doesn't have a use func...

**Comment by morenoh149** [comment]
```javascript
var bootstrap = require('bootstrap-styl'),
    stylus    = require('gulp-stylus');

gulp.task('styles', function () {
  gulp.src('./css/**/*')
    .pipe(stylus())
    .pipe(gulp.dest('./css/build'));
});
```
assuming you placed bootstrap-stylus files under `./css/` it should all get bundled up.

**Comment by maxmx** [comment]
thx @morenoh149
