### ISSUE TITLE
Conflicting module names

### ISSUE THREAD

**Issue by GCheung55** [maxmx/bootstrap-stylus#105]
`bootstrap-stylus` has conflicting module names because they aren't under `bootstrap` namespace.

For example, an existing path containing a module named `variables` could already be established so `bootstrap/variables`  doesn't get loaded in `bootstrap/index`.

To prevent this kind of conflict, the modules should be a full path to the module like:

```
...
@import "bootstrap/variables"
@import "bootstrap/mixins"
...
```

and in `bootstrap/mixins/`

```
...
@import "bootstrap/mixins/gradients"
...
```

**Comment by GCheung55** [comment]
@maxmx and @kane-c: any thoughts here?

**Comment by maxmx** [comment]
This isn't like in sass where the root directory would have been added to the path. Unless I'm mistaken I think all the imports in the index.styl are relative no?

**Comment by GCheung55** [comment]
I believe that to be partially incorrect.

Assume the following example path:
`somePath/mixins.styl`

`somePath` is included or set as a "paths" value via the JS API (https://learnboost.github.io/stylus/docs/js.html#includepath). When `bootstrap-stylus` `index.styl` imports `mixins`, it would instead import `somePath/mixins.styl`.

If `somePath` directory was not included or set as a "paths" value then the mixins.styl relative to index.styl would load.

**Comment by maxmx** [comment]
Right, makes sense.

You can submit a PR, I'll bump the major version since that kind of change would break all current usage of the library.

**Comment by GCheung55** [comment]
@maxmx I've already submitted a PR. :D https://github.com/maxmx/bootstrap-stylus/pull/106

**Comment by GCheung55** [comment]
@maxmx Anything I can do to move this along?

**Comment by maxmx** [comment]
Done, just had to test it locally first.

**Comment by maxmx** [comment]
Thank for the PR!

**Comment by GCheung55** [comment]
@maxmx no no, thank you!
