### ISSUE TITLE
@require mixins in modules for better dependency management

### ISSUE THREAD

**Issue by GCheung55** [maxmx/bootstrap-stylus#107]
Most of the modules have a dependency on a module in the mixins directory. But those dependencies have to be manually declared.

For example, if I wanted to use `bootstrap/carousel`, I'd have to write my stylus code like this:

```
@require "bootstrap/mixins/gradients"
@require "bootstrap/carousel"
```

It would be very helpful if the dependencies are declared/managed within the module that is being used. With the carousel example above, it just means `@require "bootstrap/mixins/gradients"` would be declared inside `bootstrap/carousel`.

**Comment by jangarcia** [comment]
+1

**Comment by maxmx** [comment]
To be considered for the BS4 port.
