### ISSUE TITLE
@extend .clearfix in mixins

### ISSUE THREAD

**Issue by Makvagabo** [maxmx/bootstrap-stylus#108]
Sass @include != Stylus @extend
Example
```stylus
container-fixed($gutter = $grid-gutter-width)
  margin-right auto
  margin-left auto
  padding-left ($gutter / 2)
  padding-right ($gutter / 2)
  @extend .clearfix
```
I think it must be that
```stylus
container-fixed($gutter = $grid-gutter-width)
  margin-right auto
  margin-left auto
  padding-left ($gutter / 2)
  padding-right ($gutter / 2)
  clearfix()
```

**Comment by jeremyben** [comment]
Actually, the less version of Bootstrap uses extends and the sass version uses mixins.
Maxime probably chose to use extends for the stylus version to avoid code duplication inherent to mixins.

I thought that extends were better than mixins for performance and compaction reasons, but [that article](https://tech.bellycard.com/blog/sass-mixins-vs-extends-the-data/) changed my mind.

**Comment by maxmx** [comment]
Extend also has a few caveats, I'm all for mixins as well.

I'm not super active on developing bootstrap stylus but I do take pull requests and merge them when they make sense.

**Comment by Blackskyliner** [comment]
As this issue already got an merged patch, I guess it can be closed.
