### ISSUE TITLE
Failed to locate @import file bootstrap/variables.styl

### ISSUE THREAD

**Issue by windkomo** [maxmx/bootstrap-stylus#114]
Hi,

I installed this with bower and I'm having trouble making it work :

Im my main `.styl` file I have :

```
@import '../bower_components/bootstrap-stylus/bootstrap/index.styl'
```

And I get the following error :
```
    7| // Core variables and mixins
    8| @import "bootstrap/variables"
--------------^
    9| @import "bootstrap/mixins"
   10|
   11| // Reset and dependencies

failed to locate @import file bootstrap/variables.styl
```

I'm building my css using gulp if that's relevant.

This is probably related to #109

**Comment by maxmx** [comment]
Go to https://github.com/stevelacy/gulp-stylus/issues/47 and use bootstrap style the same way you would use nib in these examples

**Comment by maxmx** [comment]
You'll also need to change your import so it imports bootstrap/index.styl

**Comment by maxmx** [comment]
If ever that's too much of a hassle, stick to 4.x.x until bs4 comes out
