### ISSUE TITLE
Why imported paths have "bootstrap" folder?

### ISSUE THREAD

**Issue by neysimoes** [maxmx/bootstrap-stylus#115]
The import files are not found, because don't exists bootstrap folder inside bootstrap folder.

<img width="1030" alt="captura de tela 2016-01-29 as 12 28 29" src="https://cloud.githubusercontent.com/assets/5016853/12678061/046e5ccc-c684-11e5-957e-a0120f3374e1.png">

**Comment by neysimoes** [comment]
:+1: 
https://github.com/maxmx/bootstrap-stylus/pull/116

**Comment by maxmx** [comment]
Please read all of this

https://github.com/maxmx/bootstrap-stylus/issues/72 and this https://github.com/maxmx/bootstrap-stylus/pull/81

to fully understand why these folders are there, the includePaths option in stylus fixes that.

**Comment by maxmx** [comment]
You can use a pre 4.0 version of this package if you want it working the old way it.

We'll address the paths in a less confusing manner when we convert bootstrap 4

**Comment by neysimoes** [comment]
I understand now. Thx! :+1:
