### ISSUE TITLE
navbar build fails 

### ISSUE THREAD

**Issue by slmyers** [maxmx/bootstrap-stylus#119]
I'm not an expert in stylus/css, and I did try to debug, but for the life of me I don't understand what's wrong. 

>[Module build failed: Error: /home/steve/git/youCanRelief/node_modules/bootstrap-styl/bootstrap/navbar.styl:97:47
    93| .container,
    94| .container-fluid
    95|   > .navbar-header,
    96|   > .navbar-collapse
    97|     margin-right (-($navbar-padding-horizontal))
-----------------------------------------------------^
    98|     margin-left (-($navbar-padding-horizontal))
    99| 
   100|     @media (min-width $grid-float-breakpoint)

>TypeError: expected "undefined" to be a unit, but got ident:$navbar-padding-horizontal](url)

If anyone could help that would be great.

**Comment by kane-c** [comment]
Which version of Stylus are you using?

Make sure `$navbar-padding-horizontal` is set. Include `variables.styl` or define it yourself before including `navbar.styl`

**Comment by slmyers** [comment]
To be honest I have no clue what I'm doing lol... I'm trying to use some boilerplate webpack+es6+stylus thing. However, including `variables.styl` and `forms.styl` before `navbar.styl` seems to have at least got it compiled. Thanks.

**Comment by kane-c** [comment]
No worries. Feel free to close the issue if this is sorted :)

Mind if I ask which boilerplate you're using?

**Comment by slmyers** [comment]
@kane-c https://github.com/AngularClass/NG6-starter

**Comment by kane-c** [comment]
Thanks. I'll check it out!
