### ISSUE TITLE
Question: which files just for the Bootstrap grid?

### ISSUE THREAD

**Issue by cjaoude** [maxmx/bootstrap-stylus#128]
What is the minimum set of files just to have the bootstrap grid? (.row, .col, etc)

Tbx

**Comment by kane-c** [comment]
Try the suggestions here: https://github.com/twbs/bootstrap-sass/issues/651

This project mirrors the structure of the official Bootstrap, so the same rules apply.

**Comment by cjaoude** [comment]
tnx, how accurate is this port of bootstrap to stylus? for example, drop-in replacement for the grid & forms?

it'd be great to off-ramp bootstrap in a clean way.

**Comment by kane-c** [comment]
Very accurate - it's a line by line port :)
