### ISSUE TITLE
Error with Webpack  Can't resolve '../fonts/glyphicons

### ISSUE THREAD

**Issue by laggingreflex** [maxmx/bootstrap-stylus#129]
I'm trying to use this with Webpack. I looked at another webpack issue #122 but mine seems different.

I'm getting this error:

```
ERROR in ./~/css-loader?importLoaders=3!./~/postcss-loader!/~/namespace-css-module-loader!/~/stylus-loader!./src/client/app/template/header/style.styl
Module not found: Error: Can't resolve '../fonts/glyphicons-halflings-regular.eot' in 'C:\...\src\client\app\template\header'
 @ ./~/css-loader?importLoaders=3!./~/postcss-loader!/~/namespace-css-module-loader!/~/stylus-loader!./src/client/app/template/header/style.styl 6:5580-5632 6:5655-5707
 @ ./src/client/app/template/header/style.styl
 @ ./src/client/app/template/header/index.js
 @ ./src/client/index.js
```

The `Can't resolve '../fonts/glyphicons-halflings-regular.eot'` indicates that it's trying to load that font file, which actually resides in the `node_modules/bootstrap-styl/fonts` dir, but it's trying to resolve it from my app's templates dir. 

---

I also notice that there's a variable
```styl
$icon-font-path ?=         "../fonts/"
```
and so I tried changing it before importing
```styl
$icon-font-path =         "bootstrap/fonts/"
@import bootstrap
```
but then the error becomes `Can't resolve './bootstrap/fonts/glyphicons-` -- it adds `./` meaning it's still looking relative to my app's templates dir.

**Comment by laggingreflex** [comment]
Ahh, this worked:
```styl
$icon-font-path =         "~bootstrap-styl/fonts/"
@import bootstrap
```

**Comment by Vivek205** [comment]
hhjhj

**Comment by italomoralesf** [comment]
It is not a fixed folder, it enters node_modules and observes the real route.
In my case it is:
```
//** Load fonts from this directory.
@icon-font-path:          "~bootstrap-sass/assets/fonts/bootstrap/";
```

This is done in the file `variables.less`

**Comment by jo-soft** [comment]
@italomoralesf   i guess you mean 
`$icon-font-path:          "~bootstrap-sass/assets/fonts/bootstrap/"` ?

**Comment by dangxuanphuc** [comment]
I followed [the recommendation](https://github.com/rails/webpacker/issues/1119#issuecomment-352388302) on [#1119](https://github.com/rails/webpacker/issues/1119) and added `resolve-url-loader` and that helped in my case.

**Comment by smshaheryar** [comment]
hello,
i am developing a website in react js but i am getting an error


./src/custom.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/custom.scss)
Module not found: Can't resolve 'bootstrap-style/fonts/glyphicons-halflings-regular.eot' in 'D:\work\frontend-joeyco\src'


can please anyone helpme
thankyou in advance

**Comment by DebugTheCode** [comment]
@smshaheryar follow @jo-soft 's answer. This worked for me.
