### ISSUE TITLE
Navbar bug

### ISSUE THREAD

**Issue by hugofabricio** [maxmx/bootstrap-stylus#85]
Hi,

The navbar is with bug in Mobile when you put navbar-right

**Comment by morenoh149** [comment]
provide a code snippit or demo

**Comment by kane-c** [comment]
Which browser and version? If you could please provide some code or a live sample that would be helpful.

I've been using `navbar-right` quite often and haven't run into any issues yet.

**Comment by hugofabricio** [comment]
I tested it on Safari, Chrome and Firefox.

![Uploading Captura de Tela 2015-01-11 às 09.01.03.png . . .]()
![Uploading Captura de Tela 2015-01-11 às 09.01.29.png . . .]()

**Comment by morenoh149** [comment]
@hugofabricio whats the bug exactly?

**Comment by hugofabricio** [comment]
When we use the navbar-right class in responsive menu it is not 100%.

**Comment by morenoh149** [comment]
@hugofabricio you want to make the text justified right. Not the entire drop-down. Try http://devdocs.io/css/text-align Right

**Comment by maxmx** [comment]
I think he's saying that the drop down menu should be the same width as the viewport. Floated element have to set their widths explicitly, may be a bug.

If you do a fix, please open a PR.

**Comment by hugofabricio** [comment]
That's right, sorry for my English, I'm not using the bootstrap text-right, I'm just stating that the menu by the cell is not 100% as is the right to the bootstrap.

Menu correct

https://dl.dropboxusercontent.com/u/70211357/Captura%20de%20Tela%202015-01-12%20%C3%A0s%2018.16.04.png

**Comment by kane-c** [comment]
Could you please post the HTML for your navbar?

**Comment by hugofabricio** [comment]
<nav class="navbar navbar-default">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#">Brand</a>
					</div>
					<div class="collapse navbar-collapse" id="menu">
						<ul class="nav navbar-nav navbar-right">
							<li class="active"><a href="index.html">Home</a></li>
							<li><a href="about.html">Quem Somos</a></li>
							<li><a href="buildings.html">Imóveis</a></li>
							<li><a href="sales.html">Venda Conosco</a></li>
							<li><a href="contact.html">Contato</a></li>
						</ul>
					</div>
				</div>
			</nav>

**Comment by kane-c** [comment]
I believe this is fixed in #89. Specifically [these changes to `.navbar-left` and `.navbar-right`](https://github.com/kane-c/bootstrap-stylus/commit/8a96c151ab8d35eef8bf08199c0f7e01a9398ecf#diff-9a6119ceeeced4415b8fb27ae9dc2048)
